version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-run:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: sudo npm i -g @adonisjs/cli
            - run: adonis migration:run
            - run: npm run build
            - run: npm run start
workflows:
    build-and-test:
      jobs:
        - build-and-run
